# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b136f08de9540bd139b745aa15cb4043"
name = "Recommendation for Email"
application_url = "https://camosignal-recommendation-email.onrender.com"
embedded = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/fulfillment_events/create"
  topics = [ "fulfillment_events/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/fulfilled"
  topics = [ "orders/fulfilled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_products,read_inventory,read_fulfillments,read_customers,write_customers"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://camosignal-recommendation-email.onrender.com/auth/callback"
]
